export const INDIA_STATES_UTS = [
  // States
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  // Union Territories
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi (NCT)",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const INDIA_CITIES = [
  "Agra", "Ahmedabad", "Ajmer", "Aligarh", "Allahabad (Prayagraj)",
  "Amravati", "Amritsar", "Aurangabad", "Bangalore", "Bareilly",
  "Bhubaneswar", "Bhopal", "Chandigarh", "Chennai", "Coimbatore",
  "Cuttack", "Dehradun", "Dhanbad", "Durgapur", "Erode",
  "Faridabad", "Gandhinagar", "Gorakhpur", "Gurgaon (Gurugram)",
  "Guwahati", "Gwalior", "Howrah", "Hubballi", "Hyderabad",
  "Indore", "Jabalpur", "Jaipur", "Jalandhar", "Jammu", "Jamnagar",
  "Jamshedpur", "Jodhpur", "Kanpur", "Kochi", "Kolkata",
  "Kozhikode (Calicut)", "Kota", "Lucknow", "Ludhiana", "Madurai",
  "Mangaluru", "Mathura", "Meerut", "Mumbai", "Mysuru (Mysore)",
  "Nagpur", "Nashik", "Navi Mumbai", "Noida", "Patna",
  "Pimpri-Chinchwad", "Pune", "Raipur", "Rajkot", "Ranchi",
  "Saharanpur", "Salem", "Shillong", "Shimla", "Siliguri",
  "Solapur", "Srinagar", "Surat", "Thane", "Thiruvananthapuram",
  "Tiruchirappalli", "Tirunelveli", "Tiruppur", "Udaipur",
  "Vadodara (Baroda)", "Varanasi", "Vijayawada", "Visakhapatnam",
  "Warangal",
];

export const ALL_INDIA_LOCATIONS = [...INDIA_STATES_UTS, ...INDIA_CITIES];
